/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portable_fingerprint_scanner_client;

import java.awt.BorderLayout;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.BadLocationException;

/**
 *
 * @author admin
 */
public class AttendanceDateGUI extends javax.swing.JPanel {

    /**
     * Creates new form AttendanceDateGUI
     */
    BiometricsGUI mainGUI;
    public AttendanceDateGUI(BiometricsGUI gui) {
        initComponents();
        mainGUI=gui;
        Date date = new Date();
        jtxtDate.setText(new SimpleDateFormat("dd-MM-yyyy").format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblHiUser = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();
        jbtnProceed = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jbtnDash = new javax.swing.JButton();
        jButtonBS = new javax.swing.JButton();
        jtxtDate = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jlblHiUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblHiUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHiUser.setText("Attendance Date");
        jPanel2.add(jlblHiUser, java.awt.BorderLayout.CENTER);

        jbtnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnBack.setMargin(new java.awt.Insets(15, 14, 15, 14));
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBack, java.awt.BorderLayout.WEST);

        jbtnLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLogout.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jbtnLogout.setText("Logout");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnLogout, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jbtnProceed.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnProceed.setText("Proceed");
        jbtnProceed.setMargin(new java.awt.Insets(30, 14, 30, 14));
        jbtnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProceedActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnProceed, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Date (DD-MM-YYYY)");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3, 15, 25));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton0);

        jbtnDash.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDash.setText("-");
        jbtnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDashActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDash);

        jButtonBS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBS.setText("<--");
        jButtonBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBSActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonBS);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jtxtDate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtxtDate.setToolTipText("DD-MM-YYYY");
        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDate, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtDate.replaceSelection("1");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("2");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("3");
        jtxtDate.requestFocus();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("4");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("5");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("6");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("7");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("8");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("9");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("0");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBSActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(jtxtDate.getCaretPosition()>0)
            jtxtDate.getDocument().remove(jtxtDate.getCaretPosition()-1, 1);
        } catch (BadLocationException ex) {
            Logger.getLogger(InitialProfessorAuthenticationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jButtonBSActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        // TODO add your handling code here:
        System.out.println("hiii");
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jbtnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDashActionPerformed
        // TODO add your handling code here:
        jtxtDate.replaceSelection("-");
        jtxtDate.requestFocus();
    }//GEN-LAST:event_jbtnDashActionPerformed

    private void jbtnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProceedActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        sdf.setLenient(false);
        try
        {
            Date AttDate=sdf.parse(jtxtDate.getText());
            System.out.println(AttDate.toString());
            Date CurrDate=new Date();
            
            System.out.println(CurrDate.toString());
            System.out.println(CurrDate.after(AttDate));
            if(CurrDate.before(AttDate))
            {
                UIManager.put("OptionPane.messageFont",new FontUIResource(new Font("Tahoma", Font.PLAIN, 24)));
                UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("Tahoma",Font.PLAIN,24)));
                JOptionPane.showMessageDialog(null, "Future Date not allowed");
                return;
            }
        }
        catch(Exception ex)
        {
            UIManager.put("OptionPane.messageFont",new FontUIResource(new Font("Tahoma", Font.PLAIN, 24)));
            UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("Tahoma",Font.PLAIN,24)));
            JOptionPane.showMessageDialog(null, "Please enter valid Date");
            return;
        }
        try {
            mainGUI.attendanceSheet.AttendanceDate=sdf.format(sdf.parse(jtxtDate.getText()));
            System.out.println("date haresh :"+ sdf.format(sdf.parse(jtxtDate.getText())));
        } catch (ParseException ex) {
            Logger.getLogger(AttendanceDateGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainGUI.remove(mainGUI.currJPanel);
        mainGUI.currJPanel=new AttendanceSheetGUI(mainGUI);
        mainGUI.add(mainGUI.currJPanel,BorderLayout.CENTER);
        mainGUI.validate();
        mainGUI.stackPanel.push(this);
        
    }//GEN-LAST:event_jbtnProceedActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        mainGUI.remove(mainGUI.currJPanel);
        mainGUI.currJPanel=mainGUI.stackPanel.pop();
        mainGUI.add(mainGUI.currJPanel);
        mainGUI.validate();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        // TODO add your handling code here:
        mainGUI.prof=null;
        mainGUI.attendanceSheet=null;
        mainGUI.stackPanel.clear();
        mainGUI.remove(mainGUI.currJPanel);
        mainGUI.currJPanel=new InitialProfessorAuthenticationGUI(mainGUI);
        mainGUI.add(mainGUI.currJPanel);
        mainGUI.repaint();
        mainGUI.validate();
    }//GEN-LAST:event_jbtnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDash;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnProceed;
    private javax.swing.JLabel jlblHiUser;
    private javax.swing.JTextField jtxtDate;
    // End of variables declaration//GEN-END:variables
}
