/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portable_fingerprint_scanner_client;

import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class AttendanceSubmittedGUI extends javax.swing.JPanel {

    /**
     * Creates new form AttendanceSubmittedGUI
     */
    BiometricsGUI mainGUI;
    public AttendanceSubmittedGUI(BiometricsGUI mainGUI) {
        this.mainGUI=mainGUI;
        initComponents();
        jlblAttendanceSheetId.setText("Attendance Sheet Id : " + mainGUI.attendanceSheet.AttendanceSheetId);
        jlblBatch.setText("Batch : " + mainGUI.attendanceSheet.BatchName);
        jlblSubject.setText("Subject : " + mainGUI.attendanceSheet.SubName);
        jlblDate.setText("Attendance Date : " + mainGUI.attendanceSheet.AttendanceDate);
        jlblTotalStudent.setText("Total Student : " + mainGUI.attendanceSheet.StudentAttInfoList.size());
        int presentcount=0;
        for(int i=0;i<mainGUI.attendanceSheet.StudentAttInfoList.size();i++)
        {
            if(mainGUI.attendanceSheet.StudentAttInfoList.get(i).Presence==true)
                presentcount++;
        }
        
        jlblPresentStudent.setText("Total Present : " + presentcount);
        jlblAbsentStudent.setText("Total Absent : " + (mainGUI.attendanceSheet.StudentAttInfoList.size() -presentcount));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblAttendanceSheetId = new javax.swing.JLabel();
        jlblBatch = new javax.swing.JLabel();
        jlblSubject = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jlblTotalStudent = new javax.swing.JLabel();
        jlblPresentStudent = new javax.swing.JLabel();
        jlblAbsentStudent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnLogout = new javax.swing.JButton();
        jbtnNew = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout(10, 10));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Summary : ");
        jPanel2.add(jLabel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jlblAttendanceSheetId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAttendanceSheetId.setText("Attendance Sheet Id :");
        jPanel4.add(jlblAttendanceSheetId);

        jlblBatch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblBatch.setText("Batch :");
        jPanel4.add(jlblBatch);

        jlblSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubject.setText("Subject :");
        jPanel4.add(jlblSubject);

        jlblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblDate.setText("Date :");
        jPanel4.add(jlblDate);

        jlblTotalStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotalStudent.setText("Total Student :");
        jPanel4.add(jlblTotalStudent);

        jlblPresentStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblPresentStudent.setForeground(new java.awt.Color(0, 153, 51));
        jlblPresentStudent.setText("Present Student :");
        jPanel4.add(jlblPresentStudent);

        jlblAbsentStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAbsentStudent.setForeground(new java.awt.Color(204, 0, 0));
        jlblAbsentStudent.setText("Absent Student :");
        jPanel4.add(jlblAbsentStudent);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jbtnLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLogout.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jbtnLogout.setText("Logout");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogout, java.awt.BorderLayout.NORTH);

        jbtnNew.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnNew.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jbtnNew.setText("Record New Attendance");
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNew, java.awt.BorderLayout.SOUTH);
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 10));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("<html>Attendance Submitted<br>Successfully !!!</html>");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
        // TODO add your handling code here:
        mainGUI.remove(mainGUI.currJPanel);
        mainGUI.currJPanel=new ProfessorBatchSubjectGUI(mainGUI);
        mainGUI.add(mainGUI.currJPanel);
        mainGUI.repaint();
        mainGUI.validate();
    }//GEN-LAST:event_jbtnNewActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        // TODO add your handling code here:
        mainGUI.prof=null;
        mainGUI.attendanceSheet=null;
        mainGUI.stackPanel.clear();
        mainGUI.remove(mainGUI.currJPanel);
        mainGUI.currJPanel=new InitialProfessorAuthenticationGUI(mainGUI);
        mainGUI.add(mainGUI.currJPanel);
        mainGUI.repaint();
        mainGUI.validate();
    }//GEN-LAST:event_jbtnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JLabel jlblAbsentStudent;
    private javax.swing.JLabel jlblAttendanceSheetId;
    private javax.swing.JLabel jlblBatch;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblPresentStudent;
    private javax.swing.JLabel jlblSubject;
    private javax.swing.JLabel jlblTotalStudent;
    // End of variables declaration//GEN-END:variables
}
