/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portable_fingerprint_scanner_client;

import EntityPackage.Professor;
import java.awt.BorderLayout;
import java.awt.Font;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.BadLocationException;

/**
 *
 * @author admin
 */
public class InitialProfessorAuthenticationGUI extends javax.swing.JPanel {

    /**
     * Creates new form InitialProfessorAuthenticationGUI
     */
    BiometricsGUI mainGUI;
    Boolean LoadProfessorFlag=false;
    public InitialProfessorAuthenticationGUI(BiometricsGUI gui) {
        initComponents();
        setBorder(BorderFactory.createEmptyBorder(10, 5, 10, 5));
        mainGUI=gui;
    }
public void loadProfessorFingerPrint(int profId)
    {
        try
        {
            Thread t=new Thread(new Runnable() {
                @Override
                public void run() {
                    try{
                        LoadProfessorFlag=false;
                        Socket sock=new Socket("192.168.43.189",9899);
                        ObjectInputStream inputFromServer=new ObjectInputStream(sock.getInputStream());
                        ObjectOutputStream outputToServer=new ObjectOutputStream(sock.getOutputStream());
                        BiometricClientServerCommands bcsCommand=new BiometricClientServerCommands();
                        outputToServer.writeInt(bcsCommand.LOAD_PROFESSOR_FINGERPRINT);
                        outputToServer.writeInt(profId);
                        outputToServer.flush();
                        int result=inputFromServer.readInt();
                        if(result==bcsCommand.LOAD_PROFESSOR_FINGERPRINT_SUCCESSFUL)
                        {
                            mainGUI.prof=(Professor)inputFromServer.readObject();
                            System.out.println(mainGUI.prof.FirstName);
                            LoadProfessorFlag=true;
                            
                        }
                        else
                        {
                            
                        }
                    }    
                    catch(Exception e)
                    {
                            e.printStackTrace();
                            
                    }
                }
            });
            t.start();
            t.join();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnStartProfAuth = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtProfId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonBS = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Record Attendance");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jbtnStartProfAuth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnStartProfAuth.setText("Start Professor Authentication");
        jbtnStartProfAuth.setMargin(new java.awt.Insets(30, 14, 30, 14));
        jbtnStartProfAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartProfAuthActionPerformed(evt);
            }
        });
        add(jbtnStartProfAuth, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));
        jPanel2.setBorder(BorderFactory.createEmptyBorder(10, 5, 10, 5));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));
        jPanel1.setBorder(BorderFactory.createEmptyBorder(20, 5, 20, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Professor ID : ");
        jPanel1.add(jLabel2, java.awt.BorderLayout.NORTH);

        jtxtProfId.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jPanel1.add(jtxtProfId, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(4, 3, 40, 25));
        jPanel3.setBorder(BorderFactory.createEmptyBorder(15, 25, 15, 25));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton0);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jButtonBS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBS.setText("BackSp");
        jButtonBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBSActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBS);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtProfId.replaceSelection("1");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("2");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("3");
        jtxtProfId.requestFocus();
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("4");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("5");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("6");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("7");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("8");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("9");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:                                         
        jtxtProfId.replaceSelection("0");
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBSActionPerformed
        // TODO add your handling code here:                                     
        try {
            // TODO add your handling code here:
            if(jtxtProfId.getCaretPosition()>0)
                jtxtProfId.getDocument().remove(jtxtProfId.getCaretPosition()-1, 1);
        } catch (BadLocationException ex) {
            Logger.getLogger(InitialProfessorAuthenticationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtProfId.requestFocus();
    }//GEN-LAST:event_jButtonBSActionPerformed

    private void jbtnStartProfAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartProfAuthActionPerformed
        // TODO add your handling code here:
        int profId=Integer.parseInt(jtxtProfId.getText());
        loadProfessorFingerPrint(profId);
        if(LoadProfessorFlag)
        {
        try
        {
            Thread t=new Thread(new Runnable() {
                @Override
                public void run() {
                    FingerPrintScanner Serialconnector=new FingerPrintScanner();
                    //byte template[]=null;
                    //stud.FingerTemplate=new byte[498];
                    try
                    {
                        if(Serialconnector.open("COM8"))
                        {
                            Serialconnector.deleteAllFingerPrintFromDevice();
                            Serialconnector.setTemplate(0, mainGUI.prof.FingerTemplate);
                            while(true)
                            {
                                System.out.println("Starting 1_1 verify");
                                boolean result=Serialconnector.verify1_1(0);
                                System.out.println("resullt : "+result);
                                if(result)
                                {
                                    mainGUI.remove(mainGUI.currJPanel);
                                    mainGUI.currJPanel=new ProfessorBatchSubjectGUI(mainGUI);
                                    mainGUI.add(mainGUI.currJPanel,BorderLayout.CENTER);
                                    mainGUI.validate();
                                    break;
                                }
                                else
                                {
                                    UIManager.put("OptionPane.messageFont",new FontUIResource(new Font("Tahoma", Font.PLAIN, 24)));
                                    UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("Tahoma",Font.PLAIN,24)));
                                    int val=JOptionPane.showConfirmDialog(null, "<html>Authentication failed.<br/> Do you want to retry?</html>", "Authentication failed", JOptionPane.YES_NO_OPTION);
                                    if(val!=JOptionPane.YES_OPTION)
                                        break;
                                }
                            }
                        }
                        Serialconnector.close();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            t.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtnStartProfAuthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnStartProfAuth;
    private javax.swing.JTextField jtxtProfId;
    // End of variables declaration//GEN-END:variables
}
