/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_admin_application_client;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class NavigationGUI extends javax.swing.JPanel {
    GUI parentGUI;
    /**
     * Creates new form NavigationGUI
     */
    public NavigationGUI(GUI parentGUI) {
        initComponents();
        this.parentGUI=parentGUI;
        DefaultListModel<String> listModel=new DefaultListModel<>();
        listModel.addElement("Dashboard");
        listModel.addElement("Department");
        listModel.addElement("Course");
        listModel.addElement("Batch");
        listModel.addElement("Batch Mapper");
        listModel.addElement("Student");
        listModel.addElement("Professor");
        listModel.addElement("Subject");
        jlistNavigator.setModel(listModel);
        jlistNavigator.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistNavigator = new javax.swing.JList<>();

        setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jlistNavigator.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistNavigatorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistNavigator);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jlistNavigatorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistNavigatorValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
        String selectedOption=jlistNavigator.getSelectedValue();
        System.out.println(selectedOption);
        if(selectedOption.equals("Department"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new DepartmentGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Dashboard"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new DashboardGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Course"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new CourseGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Student"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new StudentGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Professor"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new ProfessorGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Subject"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new SubjectGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Batch"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new BatchGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        else if(selectedOption.equals("Batch Mapper"))
        {
            parentGUI.remove(parentGUI.currJPanel);
            parentGUI.currJPanel=new BatchMapperGUI();
            parentGUI.add(parentGUI.currJPanel,BorderLayout.CENTER);
            parentGUI.validate();
        }
        }
    }//GEN-LAST:event_jlistNavigatorValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistNavigator;
    // End of variables declaration//GEN-END:variables
}
