/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_admin_application_client;

import EntityPackage.Department;
import EntityPackage.Professor;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class ProfessorGUI extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorGUI
     */
    
    ArrayList<Department> arrDeptList;
    byte template[]=null;
    public ProfessorGUI() {
        initComponents();
        jtxtProfId.setEnabled(false);
        jtxtProfId.setText("ID will be auto-generated");
        loadDepartmentList();
        
    }
    public void loadDepartmentList()
    {
        try
        {
            Thread t=new Thread(new Runnable() {
                @Override
                public void run() {
                    try{
                        
                        Socket sock=new Socket("127.0.0.1",9898);
                        ObjectInputStream inputFromServer=new ObjectInputStream(sock.getInputStream());
                        ObjectOutputStream outputToServer=new ObjectOutputStream(sock.getOutputStream());
                        outputToServer.writeUTF("LOAD_DEPARTMENT_LIST_REQUEST");
                        outputToServer.flush();
                        
                        arrDeptList=(ArrayList<Department>)inputFromServer.readObject();
                        jcomboDepartment.removeAllItems();
                        for(int i=0;i<arrDeptList.size();i++)
                        {
                            jcomboDepartment.addItem(arrDeptList.get(i).DeptName);
                        }
                        
                    }
                    catch(Exception e)
                    {
                            e.printStackTrace();
                    }
                }
            });
            t.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtProfId = new javax.swing.JTextField();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtMiddleName = new javax.swing.JTextField();
        jbtnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtEmailId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnEnroll = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcomboDepartment = new javax.swing.JComboBox<>();

        jLabel1.setText("Add, Remove or Update Professor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Details :");

        jLabel3.setText("Professor Id :");

        jLabel4.setText("First Name :");

        jLabel5.setText("Middle Name :");

        jbtnCreate.setText("Save");
        jbtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateActionPerformed(evt);
            }
        });

        jLabel6.setText("Last Name :");

        jLabel7.setText("Email Id :");

        jLabel8.setText("Finger Print :");

        jbtnEnroll.setText("Start Scan");
        jbtnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnrollActionPerformed(evt);
            }
        });

        jLabel9.setText("Depatment :");

        jcomboDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(jbtnEnroll))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jbtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcomboDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtLastName)
                                    .addComponent(jtxtEmailId)
                                    .addComponent(jtxtFirstName)
                                    .addComponent(jtxtMiddleName)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtProfId, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtProfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcomboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jbtnEnroll))
                .addGap(26, 26, 26)
                .addComponent(jbtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateActionPerformed
        // TODO add your handling code here:

        try
        {
            Thread t=new Thread(new Runnable() {
                @Override
                public void run() {
                    try{

                        Socket sock=new Socket("127.0.0.1",9898);
                        ObjectInputStream inputFromServer=new ObjectInputStream(sock.getInputStream());
                        ObjectOutputStream outputToServer=new ObjectOutputStream(sock.getOutputStream());
                        outputToServer.writeUTF("CREATE_PROFESSOR_REQUEST");
                        Professor prof=new Professor();

                        prof.FirstName=jtxtFirstName.getText();
                        prof.MiddleName=jtxtMiddleName.getText();
                        prof.LastName=jtxtLastName.getText();
                        prof.EmailId=jtxtEmailId.getText();
                        prof.DeptId=arrDeptList.get(jcomboDepartment.getSelectedIndex()).DeptId;
                        prof.FingerTemplate=template;

                        outputToServer.writeObject(prof);
                        outputToServer.flush();
                        String result=inputFromServer.readUTF();
                        System.out.println(result);
                        if(result.equals("CREATE_PROFESSOR_SUCCESSFUL"))
                        {
                            prof.ProfId=inputFromServer.readInt();
                            System.out.println(prof.ProfId);
                        }
                        else
                        {

                        }
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            });
            t.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jbtnCreateActionPerformed

    private void jbtnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnrollActionPerformed
        // TODO add your handling code here:
        try
        {
            Thread t=new Thread(new Runnable() {
                @Override
                public void run() {
                    FingerPrintScanner Serialconnector=new FingerPrintScanner();
                    //byte template[]=null;
                    //stud.FingerTemplate=new byte[498];
                    try
                    {
                        if(Serialconnector.open("COM8"))
                        {
                            template=Serialconnector.newEnrollmentWithoutSaving();
                            System.out.println("\n"+template.length);
                            if(template.length==498)
                            {
                                for(int i=0;i<498;i++)
                                System.out.print(template[i]+"\t");

                            }
                        }
                        Serialconnector.close();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            t.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnEnrollActionPerformed

    private void jcomboDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCreate;
    private javax.swing.JButton jbtnEnroll;
    private javax.swing.JComboBox<String> jcomboDepartment;
    private javax.swing.JTextField jtxtEmailId;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtMiddleName;
    private javax.swing.JTextField jtxtProfId;
    // End of variables declaration//GEN-END:variables
}
